[package]
name = "rust-physics-engine"
version = "0.2.0"
edition = "2021"

[dependencies]
macroquad = "0.4.13"
partial-borrow = "1.0.1"
serde = { version = "1.0.215", features = ["derive"] }
toml = "0.8.19"

[profile.release]
lto = "fat"
codegen-units = 1
