ball_count_2d = 1000
ball_count_3d = 500
ball_radius = 10.0
gravity = 9.81
resistance = 0.999
bounce_amount = 0.6
max_speed = 2000.0
max_pressure = 1000.0
width = 1200.0
height = 800.0
depth = 600.0
auto_sim_steps = true
sim_steps = 1
target_fps = 60
fps_boundary = 20
delete_dist = 20.0
